add datasource_id to instructions; add screenshots
datafold/datafold-docs pull request #122
Opened 2023-02-20 22:37 UTC by leoebfolsom

Updates per @arimbr 's feedback--thank you!

2023-02-21 12:28 UTC, williebsweet requested changes
I know you are trying to block out a data source id in the image of the run, but I think it’s important to show that it aligns with the variables set in previous steps.

2023-02-21 12:28 UTC, williebsweet commented on docs/os_diff/dbt_integration.md
> +  datasource_id: XXXX
@dlawin Does this need to be tab’d inline with the prod_* cars above (inside of the data_diff block)?

2023-02-21 14:49 UTC, leoebfolsom commented on docs/os_diff/dbt_integration.md
> +  datasource_id: XXXX
You're right @williebsweet , updating this

2023-02-21 23:47 UTC, kylemcnair approved these changes

2023-02-21 23:47 UTC, dlawin approved these changes

2023-02-22 02:29 UTC, williebsweet approved these changes

2023-02-22 02:29 UTC, merged