Making the Getting Started docs more vertical
datafold/datafold-docs pull request #192
Opened 2023-07-19 23:47 UTC by leoebfolsom

The user should not be kicked to a standalone Guides section if they are dbt Core users who need to find GitHub Actions templates -- based on the premise that everything you need to, well, get started should exist in the Getting Started section.

This PR makes the Getting Started section more vertical.

2023-07-20 23:51 UTC, sungchun12 requested changes
Made a couple edits, but overall like the direction.

2023-07-20 23:51 UTC, sungchun12 commented on docs/deployment_testing/team_cloud/getting_started_for_customers/dbt/dbt_core.md
> +#### 1. Create a dbt Core integration.
I recommend include images like this from the main account. The table is really overwhelming to digest and I won't read it all. This was true when I started in my own sandbox account. I don't have settings enabled on that account for whatever reason.

![image](https://github.com/datafold/datafold-docs/assets/19176976/8c443783-5556-494a-95d9-b0e998ae1d29)

![image](https://github.com/datafold/datafold-docs/assets/19176976/e62d85ff-a77b-476d-acb6-6511759361d3)

2023-07-20 23:51 UTC, sungchun12 commented on docs/deployment_testing/team_cloud/getting_started_for_customers/dbt/dbt_core.md
> +... but the details will depend on [which CI tool](#ci-implementation-tools) you use.
Hyperlink is broken

2023-07-20 23:51 UTC, sungchun12 commented on docs/deployment_testing/team_cloud/getting_started_for_customers/dbt/dbt_core.md
> +... but the details will depend on [which CI tool](#ci-implementation-tools) you use.
I recommend including a code snippet with a github action as the default. And write, "Example Github Action"

I'd also make a note to double their base branch is `main` or `master`

2023-07-20 23:51 UTC, sungchun12 commented on docs/deployment_testing/team_cloud/getting_started_for_customers/dbt/dbt_core.md
> +#### 5. Add a Datafold command to your production CI process to upload dbt artifacts (the `manifest.json`) representing the state of the project _in the latest commit of the production branch_.
see above

2023-07-20 23:51 UTC, sungchun12 commented on docs/deployment_testing/team_cloud/getting_started_for_customers/dbt/dbt_core.md
> +datafold dbt upload --ci-config-id 123 --run-type pull_request --target-folder ./target/ --commit-sha 1e6f20d0b1337db5b6d2688c04e6d4ac
```suggestion
datafold dbt upload --ci-config-id 123 --run-type ${DATAFOLD_RUN_TYPE} --commit-sha ${GIT_SHA}
```

Keep it consistent with the template yaml

2023-07-20 23:51 UTC, sungchun12 commented on docs/deployment_testing/team_cloud/getting_started_for_customers/dbt/dbt_core.md
> +datafold dbt upload --ci-config-id 123 --run-type production --target-folder ./target/ --commit-sha 1e6f20d0b1337db5b6d2688c04e6d4ac
```suggestion
datafold dbt upload --ci-config-id 123 --run-type ${DATAFOLD_RUN_TYPE} --commit-sha ${GIT_SHA}
```

Keep it consistent with the template yaml

2023-07-20 23:51 UTC, sungchun12 commented on docs/deployment_testing/team_cloud/how_datafold_team_cloud_works.md
> +- Datafold queries your warehouse and run Data Diffs of modified models and downstreams.
```suggestion
- Datafold queries your warehouse and runs Data Diffs of modified models and other downstream impacts to data apps like Hightouch, Mode, etc.
```

2023-07-20 23:51 UTC, sungchun12 commented on docs/deployment_testing/team_cloud/how_datafold_team_cloud_works.md
>  - The results of the Data Diffs are then written directly to GitHub/GitLab and can be viewed in the Datafold Cloud application.
```suggestion
- The results of the Data Diffs are then written directly to GitHub/GitLab and more details can be viewed in the Datafold Cloud application.
```

2023-07-20 23:51 UTC, sungchun12 commented on docs/deployment_testing/team_cloud/getting_started_for_customers/dbt/dbt_core.md
> +... but the details will depend on [which CI tool](#ci-implementation-tools) you use.
It's okay if there's duplicate writing, what matters is that the reader doesn't do too much context switching.

2023-07-20 23:59 UTC, leoebfolsom commented
Thank you @sungchun12 , follow-on commits forthcoming!

2023-07-21 22:30 UTC, sungchun12 commented on docs/deployment_testing/team_cloud/getting_started_for_customers/dbt/dbt_core.md
> +#### 1. Create a dbt Core integration.
We can live this for another PR later.

2023-07-21 22:32 UTC, sungchun12 approved these changes

2023-07-21 22:34 UTC, merged