address schema future grants
datafold/datafold-docs pull request #203
Opened 2023-08-09 20:55 UTC by leoebfolsom

This issue has caused a lot of confusion during onboarding, and should be explained in the docs.

2023-08-09 21:03 UTC, sungchun12 requested changes

2023-08-09 21:03 UTC, sungchun12 commented on docs/deployment_testing/team_cloud/getting_started_for_customers/data_sources/snowflake.md
> +
Great clarifier!

In addition, can you add an example screenshot like this so the reader has a quick reference for what the end result should be in snowflake? 

![image](https://github.com/datafold/datafold-docs/assets/19176976/057252a4-dff9-410a-90d0-0e266cc3e633)

2023-08-09 21:05 UTC, sungchun12 commented on docs/deployment_testing/team_cloud/getting_started_for_customers/data_sources/snowflake.md
> +
Maybe one image for the standard full script generic version and one where you call out future schema grants

2023-08-09 22:26 UTC, vvkh commented on docs/deployment_testing/team_cloud/getting_started_for_customers/data_sources/snowflake.md
> +
> every existing _schema_

Maybe I got it wrong, but shouldn't we say "every schema with defined future grants" or something like that?
We don't really need users to do it for literally every schema they have.

2023-08-09 22:28 UTC, vvkh commented
@leoebfolsom it's great that we'll finally have this documented somewhere 👍

2023-08-09 23:19 UTC, leoebfolsom commented on docs/deployment_testing/team_cloud/getting_started_for_customers/data_sources/snowflake.md
> +
@vvkh I wasn't 100% sure, but since there is no harm on executing on all schemas ... it could actually lead to a more frictionless experience to just have them execute on all, rather than forcing them to explore which ones are actually necessary.

We can always update later if people complain (e.g., if it turns out that some users have too many schemas and it's annoying to grant future on all).

2023-08-09 23:39 UTC, leoebfolsom commented on docs/deployment_testing/team_cloud/getting_started_for_customers/data_sources/snowflake.md
> +
@sungchun12 I agree this is a good idea, but feels out of scope from the current incremental improvement I'm trying to push -- getting the bare bones information in front of onboarding users who are currently running into this problem. Could the screenshot suggestion be part of a separate PR? I'm partially requesting this because I'm trying to generate a useful screenshot and running into problems, so it's feeling like scope creep and a blocker.

2023-08-09 23:44 UTC, sungchun12 commented on docs/deployment_testing/team_cloud/getting_started_for_customers/data_sources/snowflake.md
> +
What's the current screenshot you have for reference? I can help troubleshoot

2023-08-09 23:46 UTC, leoebfolsom commented on docs/deployment_testing/team_cloud/getting_started_for_customers/data_sources/snowflake.md
> +
<img width="914" alt="Screenshot 2023-08-09 at 16 37 50" src="https://github.com/datafold/datafold-docs/assets/1799931/074f6727-57a0-4469-9953-ff7ef84fadf1">
Here is my attempt to generate a useful screenshot of the future grants -- I feels like I'm doing something wrong, because "0 objects affected" isn't what I would expect.

Generating a screenshot for the _entire_ script would be more work still to get it exactly right -- hence my request to separate from this PR your good ideas about how to improve this page overall, since this PR is intended to make a small short-term improvement--a quick win.

2023-08-09 23:46 UTC, leoebfolsom commented on docs/deployment_testing/team_cloud/getting_started_for_customers/data_sources/snowflake.md
> +
(Naturally, I wouldn't use the whole screenshot including the db and schema creation; that's just for your reference)

2023-08-09 23:48 UTC, sungchun12 commented on docs/deployment_testing/team_cloud/getting_started_for_customers/data_sources/snowflake.md
> +
That's fine. This is helpful for future reference. You can ignore adding a screenshot then

2023-08-09 23:49 UTC, leoebfolsom commented on docs/deployment_testing/team_cloud/getting_started_for_customers/data_sources/snowflake.md
> +
Thank you -- I would have happily done it if it was a quick thing, but don't think it's worth both of our time at this exact moment! I am very in favor of overhauling this whole page when we have bandwidth.

2023-08-10 00:15 UTC, sungchun12 approved these changes

2023-08-10 00:23 UTC, merged