Break up 'How to use' into multiple pages and related updates
datafold/datafold-docs pull request #53
Opened 2022-11-08 03:21 UTC by leoebfolsom

The OS Diff "How to use" page was getting pretty long as I added examples, so I broke it up into three pages:

- Command line
- TOML Config file
- Python

A few other items that followed naturally from this initial/primary goal:

- I also added Snowflake-specific TOML config instructions to the "How to use > TOML Config file" page
- I moved the "Databases we support" to its own page--hopefully this will help some new users quickly answer questions about whether this will be useful to them out of the box.
- I created a new page, "How to use > Options" because this pertains to the other three "How to use" pages.

@williebsweet ow @dlawin would you please advise how to make the `how_to_use` menu item, which is a folder, render as "How to use"? Now that it's a folder, I haven't figured out how to specify the name. (I can dig more, but figured you might know.) 

Along the same lines, I need to make the "How to use" menu item appear fourth (after "databases we support").

Thanks!

2022-11-08 03:28 UTC, leoebfolsom commented
I think everything is failing because of something I didn't do right with the docusaurus structure and the how_to_use folder as a menu item. I'll dig into it tomorrow if no one has a quick solution they can point me to.

2022-11-08 16:59 UTC, leoebfolsom commented
Thank you @erezsh, I like that direction, and I'll take a stab at it 🙌

2022-11-08 20:06 UTC, williebsweet commented
> @williebsweet ow @dlawin would you please advise how to make the how_to_use menu item, which is a folder, render as "How to use"? Now that it's a folder, I haven't figured out how to specify the name. (I can dig more, but figured you might know.)
@leoebfolsom - [this commit](https://github.com/datafold/datafold-docs/pull/53/commits/821bbd2cf7412c38cb7d5a1862e30bf21abcd45a) addresses the question above

2022-11-09 01:26 UTC, leoebfolsom commented
@erezsh I mocked up an options table. However, I wasn't sure what to put in the "config key" column. Would you please either:

- fill in that column
- point me to documentation
- let me know how to translate the CLI Switch to the syntax for config key?

I can guess, but don't want to waste my time making an assumption.

Thanks!

2022-11-09 12:36 UTC, erezsh commented
Yes, that's exactly why we need this table :)

It basically all follows the same pattern - you take the longest form, and swap the `-` for `_`. So 

```
--key-columns   ->  key_columns
--materialize-all-rows     -> materialize_all_rows
```
and so on

2022-11-09 17:06 UTC, leoebfolsom commented
@erezsh thanks! to be clear, the config keys are to be used in the TOML file?

Is there a third version for a Python use case, or does it leverage either the CLI switches or the config keys?

2022-11-09 17:37 UTC, dlawin commented
minor but the wrapping of the long form flags can look odd:
![Screen Shot 2022-11-09 at 10 36 49 AM](https://user-images.githubusercontent.com/11282254/200901172-94653424-a4f8-4e1f-b287-bed2c513d704.png)

I _think_ it's possible to force them not to wrap

2022-11-09 17:38 UTC, erezsh commented
Yes, Python and the TOML file share the same keys.

--conf and --run don't appear in the TOML or Python. But if you omit `--run` and define `run.default`, it's like calling `--run default`

2022-11-09 17:43 UTC, erezsh commented
@dlawin I agree that they shouldn't wrap

2022-11-09 17:49 UTC, erezsh requested changes
I like the direction.

I still think it would help to split them to categories. Like 'diff-related', 'table filtering', 'display options', 'misc'

2022-11-09 17:49 UTC, erezsh commented on docs/os_diff/how_to_use/options.md
> +You can use the following options to specificy the configuration of a data-diff run.
Specify

2022-11-09 17:49 UTC, erezsh commented on docs/os_diff/how_to_use/options.md
> +```
Add TOML highlighting

2022-11-09 17:49 UTC, erezsh commented on docs/os_diff/how_to_use/options.md
> +| Config key     | CLI switch                 | Description                                      | Within-Database | Cross-Database |
Fix wrapping of switches causing artifacts like

```
   --i or --
   interactive
```

2022-11-09 17:49 UTC, erezsh commented on docs/os_diff/how_to_use/options.md
> +| `conf`, `run`   | `--conf`, `--run`           | Specify the run and configuration [from a TOML file](how_to_use_with_toml.md). | ✅ | ✅ |
no equivalent config key

2022-11-09 17:49 UTC, erezsh commented on docs/os_diff/how_to_use/options.md
> +| `algorithm`   | `-a`, `--algorithm`  | Force algorithm choice. Options: `auto`, `joindiff`, `hashdiff` | ✅ |  |
algorithm is a general swithch, not just for joindiff

2022-11-09 18:06 UTC, leoebfolsom commented on docs/os_diff/how_to_use/options.md
> +| Config key     | CLI switch                 | Description                                      | Within-Database | Cross-Database |
@dlawin @erezsh I found a lot of discussion online about how the way GitHub works with markdown, there's not a great option for wrapping. I found a hacky solution that I hope you both can tolerate unless you can point me to a better option. commit forthcoming but it'll look like this:

```
| Config key | CLI&nbsp;switch&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;| Description | Within-Database | Cross-Database |
```

2022-11-09 18:08 UTC, leoebfolsom commented on docs/os_diff/how_to_use/options.md
> +```
Sorry, what do you mean by this?

2022-11-09 18:09 UTC, leoebfolsom commented
> I still think it would help to split them to categories. Like 'diff-related', 'table filtering', 'display options', 'misc'

@erezsh I tried to get at this with the additional columns but I see what you mean--let me mock something up.

2022-11-09 18:29 UTC, leoebfolsom commented
@erezsh I took some liberties with the categories. For one, I didn't think "diff-related" was meaningful because it's all basically diff-related. See what you think. I'm open to your suggestions.

I added an additional column, which is more straightforward than getting github+markdown to render subheads. Another option would be to have multiple tables, each dedicated to a category. I thought the approach I took was more straightforward for the reader (the categories aren't _that_ distinctive so as to require separate tables), but there are tradeoffs either way.

2022-11-10 00:25 UTC, erezsh commented on docs/os_diff/how_to_use/options.md
> +```
```toml
[this.is_highlighted]
so_is = "this"
```

2022-11-10 06:53 UTC, leoebfolsom commented on docs/os_diff/how_to_use/options.md
> +```
This feels like a riddle. Can you please explain more or give an example of what you would like me to add? Don't I already use both version in the example code snippet I included in the subsequent lines?

```
# Specify the default run parameters
[run.default]
  verbose = true
  stats = true
```

Sorry if I'm missing something obvious.

2022-11-10 11:28 UTC, erezsh commented
Looking good! I like the Performance category.

But I would say sample_exclusive_rows is more output or settings than performance. Also I would put the first four in Schema instead of Settings.

2022-11-10 17:34 UTC, leoebfolsom commented
> But I would say sample_exclusive_rows is more output or settings than performance. Also I would put the first four in Schema instead of Settings.

Totally agree--I misread the description earlier.

2022-11-10 17:57 UTC, erezsh commented
You're still not highlighting the TOML - You're still not highlighting the TOML - https://deploy-preview-53--datafold-docs.netlify.app/os_diff/how_to_use/how_to_use_with_toml

Does  docosaurus not support it?

2022-11-10 20:09 UTC, leoebfolsom commented
@erezsh as I said [here](https://github.com/datafold/datafold-docs/pull/53#discussion_r1018711622), I didn't understand what you meant by "highlighting the toml." I'd never heard of "highlighting" before, and in the code snippet you provided as an example, the fact that you included `toml` after the first three ticks wasn't apparent to me, so I still failed to understand. I only just now figured out what I think you want. I did this by clicking edit on your comment to see if there was something for me to discover. I'm going to try to do it now.

2022-11-10 20:11 UTC, leoebfolsom commented
@erezsh I agree it looks much better with the highlighted toml. Thanks for making me aware of this option!

2022-11-10 20:39 UTC, erezsh commented
I still don't see it highlighted in the preview

2022-11-10 20:58 UTC, leoebfolsom commented
@erezsh bummer. Looks like it's supported and would have to be added to https://github.com/highlightjs/highlight.js/tree/main/src/languages .

2022-11-10 22:25 UTC, leoebfolsom commented
@erezsh since there's not a short-term way of getting TOML highlighting, can you please approve or request additional changes?

2022-11-11 02:27 UTC, erezsh approved these changes

2022-11-11 05:02 UTC, dlawin approved these changes

2022-11-11 16:19 UTC, merged

2022-11-11 16:22 UTC, erezsh commented
Makes me wonder why we aren't using a Python highlighter, because they won't have this limitation.

2022-11-11 17:36 UTC, leoebfolsom commented
@erezsh do you mean using 
```
```python
```

instead of 

```
```toml
```

at the beginning of the TOML blocks? 

That seems to work (see this screenshot, from running the docs on localhost with that change):


<img width="626" alt="Screen Shot 2022-11-11 at 9 33 58 AM" src="https://user-images.githubusercontent.com/1799931/201397157-0c77cd69-9aac-45b2-b4d3-f3e130078134.png">

2022-11-11 17:45 UTC, erezsh commented
Actually I meant using a Python code highlighter.

But your solution is a big improvement too!