add info about how to upload artifacts via sdk
datafold/datafold-docs pull request #67
Opened 2022-12-01 07:48 UTC by leoebfolsom

I added a little explainer ([thanks to Ilia](https://datafold.slack.com/archives/C03CS4L7GSK/p1669879752434309?thread_ts=1669877641.350159&cid=C03CS4L7GSK)) about how to upload artifacts to GitHub via the SDK.

Clearly the SDK documentation is not in an ideal state, but I didn't know where else to reasonably put this, and I figured no time like the present to start adding to the SDK documentation?

2022-12-01 13:57 UTC, williebsweet commented
This seems like quite the leap:
> If your GitHub integration informs you that artifacts for a given SHA are missing and should be provided, you can accomplish this by restoring your local version of the dbt project to the state of that SHA and running `dbt compile`.


We should probably incorporate a guide on how to do that.

2022-12-01 13:58 UTC, williebsweet requested changes

2022-12-01 13:58 UTC, williebsweet commented on docs/api/content/datafold-sdk.md
> +If your GitHub integration informs you that artifacts for a given SHA are missing and should be provided, you can accomplish this by restoring your local version of the dbt project to the state of th
This seems like quite the leap

We should probably incorporate a guide on how to do that.

2022-12-01 21:21 UTC, leoebfolsom commented on docs/api/content/datafold-sdk.md
> +If your GitHub integration informs you that artifacts for a given SHA are missing and should be provided, you can accomplish this by restoring your local version of the dbt project to the state of th
@williebsweet I agree. Are you thinking:

* `git checkout` a new local branch that contains the version of the repo from a specific SHA--with specific commands/examples as guidance.
* `dbt compile` to generate a `manifest.json` (which I'm guessing is what's needed when we refer to "artifacts"
* upload that file using the sdk command provided above

?

2022-12-01 22:41 UTC, williebsweet commented on docs/api/content/datafold-sdk.md
> +If your GitHub integration informs you that artifacts for a given SHA are missing and should be provided, you can accomplish this by restoring your local version of the dbt project to the state of th
Yeah - exactly like that.

2022-12-21 07:51 UTC, vvkh commented on docs/guides/ci_guides/datafold-sdk/uploading_dbt_artifacts.md
> +
I would read "a previous commit" as literally the commit before the latest, which is not always the base branch commit. If you have multiple commits in your branch, the "previous" commit is still related to your feature branch, not the base branch.

Do you think it's worth clarifying, or maybe it's obvious for most of our customers?

2022-12-21 10:16 UTC, vvkh commented on docs/guides/ci_guides/datafold-sdk/uploading_dbt_artifacts.md
> +If artifacts from one of the commits is missing, it could be for a number of reasons, but is likely due to a failed dbt Cloud job (e.g., a test failure).
For dbt Cloud, it's either failed or not triggered (yet?) job.

For dbt Core, there are a few cases I can think of:
* They've just added their CI pipeline, and it's not yet merged into the main branch. 
* Their CI pipeline hasn't triggered for some reason.
* Their CI pipeline has failed.
* They upload artefacts via `datafold-sdk` to the wrong config id.

2022-12-21 10:19 UTC, vvkh commented on docs/guides/ci_guides/datafold-sdk/uploading_dbt_artifacts.md
> +It's important to note that this will only resolve the error if the data in both your PR and production schemas were created using the code from the commits that were used to create the artifacts! Ot
> It's important to note that this will only resolve the error if the data in both your PR and production schemas were created using the code from the commits that were used to create the artifacts!

This depends on the base commit selection strategy. If it's `latest`, we can upload a manifest for any recent commit in the base branch.

2022-12-21 10:20 UTC, vvkh commented on docs/guides/ci_guides/datafold-sdk/uploading_dbt_artifacts.md
> +The missing artifacts from the specific commit can be created and uploaded via the SDK.
I believe they can also trigger the dbt Cloud job manually. Not sure if we want to mention this approach here, though.

2022-12-21 10:26 UTC, vvkh commented on docs/guides/ci_guides/datafold-sdk/uploading_dbt_artifacts.md
> +datafold dbt upload --ci-config-id <ci_config_id> --run-type production --target-folder <artifacts_path> --commit-sha <git_sha>
`--run-type` can be `pull_request ` or `production` depending on what artefact they want to upload. We mentioned both PR and production artifacts at the beginning of the guide, so the instructions should probably be relevant for both cases, shouldn't they?

2022-12-21 10:30 UTC, vvkh commented
As there are lots of stuff depending on the `base commit selection` strategy, I wonder if we should explain the option in more detail? 

It's like `git merge` vs `git rebase`: kind of hard to explain in text, but once you visualise it, it becomes clear.

![image](https://user-images.githubusercontent.com/18095933/208883781-a9aa045a-0eaa-4336-bdcf-87f70f7b31c9.png)

2022-12-21 18:20 UTC, leoebfolsom commented
> As there are lots of stuff depending on the `base commit selection` strategy, I wonder if we should explain the option in more detail?
> 
> It's like `git merge` vs `git rebase`: kind of hard to explain in text, but once you visualise it, it becomes clear.
> 
> ![image](https://user-images.githubusercontent.com/18095933/208883781-a9aa045a-0eaa-4336-bdcf-87f70f7b31c9.png)

@vvkh I definitely agree, but I'm going to add detail about that as a separate PR, and then link to it from this one once it exists. I'm trying to avoid holding up providing the basic steps that will work for most users who run into this, even if it our explanation should be improved from here.

2022-12-21 18:21 UTC, leoebfolsom commented on docs/guides/ci_guides/datafold-sdk/uploading_dbt_artifacts.md
> +datafold dbt upload --ci-config-id <ci_config_id> --run-type production --target-folder <artifacts_path> --commit-sha <git_sha>
Nice, I will update this accordingly. 🙌

2022-12-21 18:27 UTC, leoebfolsom commented on docs/guides/ci_guides/datafold-sdk/uploading_dbt_artifacts.md
> +It's important to note that this will only resolve the error if the data in both your PR and production schemas were created using the code from the commits that were used to create the artifacts! Ot
@vvkh I see. I think the important point to emphasize here is that the commit that is uploaded should ideally be consistent with tables that are in the warehouse that were generated by a `dbt run` using that commit.

If the warehouse is in a state that's inconsistent with the `merge base` commit, it would be best to use the `latest` strategy and upload artifacts from a commit that is consistent with the current warehouse state. 

Would you agree with that?

2022-12-21 18:32 UTC, leoebfolsom commented on docs/guides/ci_guides/datafold-sdk/uploading_dbt_artifacts.md
> +
How about I change "previous" to "earlier"?

Along the lines of my other comment about `merge base` vs `latest`, ideally I would be able to speak in general terms about how Datafold compares two commits to identify different models. We can get into the details about `merge base` vs `latest` elsewhere, but I want to be able to share with the user a basic truth: that we use artifacts from two commits. And whether we use `merge base` or `latest`, there may be issues in executing the proper diffs as dictated by the artifacts _if_ the commit that represents the "current state" of the code is not consistent with the data in the warehouse.

So, I would like to stick with:

> Datafold uses the artifacts from two commits to compare your code changes: 
> 
> - A set of artifacts representing the data as would be created by the latest git commit in your PR.
> - A set of artifacts representing the data as it is in your production data, using an earlier git commit.

2022-12-21 18:33 UTC, leoebfolsom commented on docs/guides/ci_guides/datafold-sdk/uploading_dbt_artifacts.md
> +If artifacts from one of the commits is missing, it could be for a number of reasons, but is likely due to a failed dbt Cloud job (e.g., a test failure).
Thank you, I'll add notes about these possibilities. 🙌

2022-12-21 18:33 UTC, leoebfolsom commented on docs/guides/ci_guides/datafold-sdk/uploading_dbt_artifacts.md
> +The missing artifacts from the specific commit can be created and uploaded via the SDK.
I'd like to leave it to the SDK, and if we can help someone do a manual trigger ad hoc, all the better. If it becomes established as a useful approach, I'll add it to the documentation.

2022-12-21 21:45 UTC, leoebfolsom commented on docs/guides/ci_guides/datafold-sdk/uploading_dbt_artifacts.md
> +If artifacts from one of the commits is missing, it could be for a number of reasons, but is likely due to a failed dbt Cloud job (e.g., a test failure).
I think we should omit the `datafold-sdk` possibility because this guide directed at users who are encountering this error from a message in the CI/CD Datafold bot. I do understand that the same situation could be caused by a user error in `datafold-sdk`, but I don't want to confuse users who have never before tried to do anything with `datafold-sdk`.

2022-12-22 08:15 UTC, leoebfolsom commented on docs/guides/ci_guides/datafold-sdk/uploading_dbt_artifacts.md
> +It's important to note that this will only resolve the error if the data in both your PR and production schemas were created using the code from the commits that were used to create the artifacts! Ot
@vvkh I added this explanation which I hope you feel is a reasonable amount of detail to help the user understand what's going on with the merge base selection strategy?
https://github.com/datafold/datafold-docs/pull/67/files#diff-64b78bebe10e61017bb2edd6159ab81641cc38096748cff5a7c56c97a98f227cR29

2022-12-22 17:02 UTC, williebsweet approved these changes

2022-12-22 17:31 UTC, vvkh commented on docs/guides/ci_guides/datafold-sdk/uploading_dbt_artifacts.md
> +If artifacts from one of the commits is missing, it could be for a number of reasons, but is likely due to a failed dbt Cloud job (e.g., a test failure).
Sorry, I meant using `datafold-sdk` in the dbt core CI pipeline.

So a typical dbt core pipeline looks like this:
```
dbt run
datafold dbt upload --ci-config-id ${DATAFOLD_CI_CONFIG} --run-type ${DATAFOLD_RUN_TYPE} --target-folder ./target/ --commit-sha ${GIT_SHA}
```

Note that we provide several parameters to the `datafold` CLI. Each parameter can be wrong, leading to us not receiving the artefact.

2022-12-22 22:37 UTC, leoebfolsom commented on docs/guides/ci_guides/datafold-sdk/uploading_dbt_artifacts.md
> +If artifacts from one of the commits is missing, it could be for a number of reasons, but is likely due to a failed dbt Cloud job (e.g., a test failure).
Got it. I've added a line and then am merging with @williebsweet 's approval. ✅ 

@vvkh don't hesitate to reach out if you suggest incremental improvements from this version, but I don't want to wait on this being out in the world! Thank you so much for your feedback!

2022-12-22 22:37 UTC, merged