reorganize/rework advanced config
datafold/datafold-docs pull request #75
Opened 2022-12-08 23:17 UTC by dlawin

Separate into distinct sections for Primary Key and Other

Separate the other configs into separate sections

2022-12-09 00:41 UTC, kylemcnair commented on docs/integrations/orchestration/dbt_adv_config.md
>  ### **Tag primary keys in dbt model**
```suggestion
### **Tag primary keys in dbt models**
```

2022-12-09 13:50 UTC, williebsweet requested changes
Left a couple of comments - only two require follow-up from you.

Good call on adding the language type to the code blocks.

2022-12-09 13:50 UTC, williebsweet commented on docs/integrations/orchestration/dbt_adv_config.md
> +In the case of a compound Primary Key, you can assign a second column (or more):
@dlawin Is this a repeat of the above?

2022-12-09 13:50 UTC, williebsweet commented on docs/integrations/orchestration/dbt_adv_config.md
> +$ export DATAFOLD_APIKEY=Ratc0zd27hjkhjfgPU3AxZ
Should we clarify that this would be `<your_primary_key>`

2022-12-09 13:50 UTC, williebsweet commented on docs/integrations/orchestration/dbt_adv_config.md
> +## Other Advanced Configuration
🙌  Thank you for adding this as a section!

2022-12-09 20:06 UTC, dlawin commented on docs/integrations/orchestration/dbt_adv_config.md
> +In the case of a compound Primary Key, you can assign a second column (or more):
kinda, it's saying the same thing but for metadata vs. tags

2022-12-09 20:08 UTC, dlawin commented on docs/integrations/orchestration/dbt_adv_config.md
> +$ export DATAFOLD_APIKEY=Ratc0zd27hjkhjfgPU3AxZ
yep good point fixed

2022-12-09 20:09 UTC, dlawin commented on docs/integrations/orchestration/dbt_adv_config.md
> +In the case of a compound Primary Key, you can assign a second column (or more):
I'm going to resolve this but feel free to reopen

2022-12-09 20:10 UTC, dlawin commented
> Would it make sense to group `dbt - Adv. configs` and `Slim CI` under a single `advanced configs` section?
> 
> As is `dbt Cloud`, `dbt Core`, and `datafold-sdk` make sense to me under the Orchestration heading, but the other two seem a bit out on their own.

I lean towards agreeing here, interested in what @leoebfolsom thinks

2022-12-09 20:13 UTC, kylemcnair commented
> > Would it make sense to group `dbt - Adv. configs` and `Slim CI` under a single `advanced configs` section?
> > As is `dbt Cloud`, `dbt Core`, and `datafold-sdk` make sense to me under the Orchestration heading, but the other two seem a bit out on their own.
> 
> I lean towards agreeing here, interested in what @leoebfolsom thinks

To be clear, I was thinking like:
* orchestration
  * dbt-cloud
  * dbt-core
  * datafold-skd
  * advanced config
    * dbt advanced
    * slim ci

2022-12-09 20:38 UTC, dlawin commented
> > > Would it make sense to group `dbt - Adv. configs` and `Slim CI` under a single `advanced configs` section?
> > > As is `dbt Cloud`, `dbt Core`, and `datafold-sdk` make sense to me under the Orchestration heading, but the other two seem a bit out on their own.
> > 
> > 
> > I lean towards agreeing here, interested in what @leoebfolsom thinks
> 
> To be clear, I was thinking like:
> 
> * orchestration
>   
>   * dbt-cloud
>   * dbt-core
>   * datafold-skd
>   * advanced config
>     
>     * dbt advanced
>     * slim ci

ohhh yeah that's a great idea. Just nesting the menu

2022-12-12 19:34 UTC, dlawin commented
> > > > Would it make sense to group `dbt - Adv. configs` and `Slim CI` under a single `advanced configs` section?
> > > > As is `dbt Cloud`, `dbt Core`, and `datafold-sdk` make sense to me under the Orchestration heading, but the other two seem a bit out on their own.
> > > 
> > > 
> > > I lean towards agreeing here, interested in what @leoebfolsom thinks
> > 
> > 
> > To be clear, I was thinking like:
> > 
> > * orchestration
> >   
> >   * dbt-cloud
> >   * dbt-core
> >   * datafold-skd
> >   * advanced config
> >     
> >     * dbt advanced
> >     * slim ci
> 
> ohhh yeah that's a great idea. Just nesting the menu

I'm going to take this as a follow up ticket

2022-12-14 22:40 UTC, williebsweet approved these changes

2022-12-14 22:41 UTC, merged